Prometheus hpa
caicloud/contrib pull request #4
Opened 2016-12-14 07:36 UTC by mqliang

@ddysher @Pendoragon 已自测通过，PTAL

只需要review第二个commit即可，其他的commit是vendor，script相关的。
大部分代码是从k8s的controller里copy出来的，主要的改动在podautoscalar/metrics/metrics_client.go里

2016-12-21 04:27 UTC, reAsOn2010 requested changes

2016-12-21 04:27 UTC, reAsOn2010 commented on prometheus-hpa/podautoscaler/metrics/metrics_client.go
> +	DefaultPrometheusAddress    = "http://prometheus-0.kube-system.svc:9090"
这个不可配置？

2016-12-21 04:27 UTC, reAsOn2010 commented on prometheus-hpa/podautoscaler/metrics/metrics_client.go
> +	for podName := range podNames {
strings.Join()

2016-12-21 04:27 UTC, reAsOn2010 commented on prometheus-hpa/podautoscaler/metrics/metrics_client.go
> +	for podName := range podNames {
还有后面其他的这样的写法

2016-12-21 04:29 UTC, reAsOn2010 commented
需要测试代码

2016-12-21 10:00 UTC, harryge00 commented on prometheus-hpa/podautoscaler/horizontal.go
> +	if math.Abs(1.0-usageRatio) > tolerance {
需要 1.0 去减吗？

2016-12-21 10:00 UTC, harryge00 commented on prometheus-hpa/podautoscaler/horizontal.go
> +	cpuDesiredReplicas := int32(0)
和`cpuDesiredReplicas := 0` 的区别呐。。。

2016-12-21 10:20 UTC, harryge00 commented on prometheus-hpa/podautoscaler/horizontal.go
> +func (a *HorizontalController) computeReplicasForCPUUtilization(hpa *autoscalingv1.HorizontalPodAutoscaler, scale *extensionv1beta1.Scale) (int32, *int32, time.Time, error) {
加个注释呗 并不知道你怎么算的。。。

2016-12-22 07:22 UTC, mqliang commented on prometheus-hpa/podautoscaler/horizontal.go
> +func (a *HorizontalController) computeReplicasForCPUUtilization(hpa *autoscalingv1.HorizontalPodAutoscaler, scale *extensionv1beta1.Scale) (int32, *int32, time.Time, error) {
官方文档有 http://kubernetes.io/docs/user-guide/horizontal-pod-autoscaling/

2016-12-22 07:22 UTC, mqliang commented on prometheus-hpa/podautoscaler/horizontal.go
> +	cpuDesiredReplicas := int32(0)
这个文件是从k8s自带的heapester的hpa controller里copy出来的

2016-12-22 07:22 UTC, mqliang commented on prometheus-hpa/podautoscaler/horizontal.go
> +	if math.Abs(1.0-usageRatio) > tolerance {
这个文件是从k8s自带的heapester的hpa controller里copy出来的

2016-12-22 07:29 UTC, reAsOn2010 approved these changes

2016-12-22 07:34 UTC, mqliang commented
@reAsOn2010
> 需要测试代码
单元测试还是e2e测试？单元测试的话，整个horizonal文件都是从k8s自带的hpa controller里copy出来的。我只改了metrics_client.go， 把heapster换成了prometheus，然后拿到query结果以后换算了一下单位（k8s和heapster里的100m cpu == prometheus里的0.1 cpu，所以我拿到prometheus的query以后乘了1000）

2016-12-22 07:37 UTC, reAsOn2010 commented
单元测试跑过吗？ 或者有没有入口可以方便的跑一把的

2016-12-22 07:37 UTC, reAsOn2010 commented
甚至你把测试 copy 一份都行

2017-10-26 15:16 UTC, closed without merging